# ----------- CONFIGURABLE START -----------
title:            "浅灰色的草帽"
description:      "HI 电影的世界、书中之屋、进入二次元"
url:              https://downeyye.github.io # 域名
signoff:          "downeyye" # Your name
facebook_appid:   #downeyye
google_analytics: UA-101222464-1
share:            true 
# 分页
paginate: 9
paginate_path: "downeyyepage:num"
gems: [jekyll-paginate]
links:
  - name:         HI这是全部
    url:          /
    external:     false
  - name:         HI这是电影
    url:          /book
    external:     false
  - name:         HI这是动漫
    url:          /road
    external:     false
  - name:         HI这里有更新
    url:          /archives
    external:     false
  - name:         关于
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
